<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblogaleks"
 *
 * Auto generated by Extension Builder 2019-06-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Blog Extension Aleksandra',
    'description' => 'Extension based on the Extension book.',
    'category' => 'plugin',
    'author' => 'Aleksandra Fey',
    'author_email' => 'aleksandra.fey@ion2s.com',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
